media:
  - name: blog-images
    label: Blog Images
    input: public/images/blog
    output: /images/blog
    path: /images/blog

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: src/content/posts
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
      - name: pubDate
        label: Publication Date
        type: date
      - name: author
        label: Author
        type: string
      - name: image
        label: Featured Image
        type: object
        fields:
          - name: url
            label: Image URL
            type: string
          - name: alt
            label: Alt Text
            type: string
      - name: tags
        label: Tags
        type: list
      - name: body
        label: Content
        type: rich-text
        required: true

  - name: hero-section
    label: Hero Section
    type: file
    path: src/content/homeSections/hero.md
    fields:
      - name: title
        label: Title
        type: string
      - name: order
        label: Order
        type: number
      - name: section
        label: Section Type
        type: string
      - name: body
        label: Content
        type: rich-text

  - name: about-section
    label: About Section
    type: file
    path: src/content/homeSections/about.md
    fields:
      - name: title
        label: Title
        type: string
      - name: order
        label: Order
        type: number
      - name: section
        label: Section Type
        type: string
      - name: body
        label: Content
        type: rich-text

  - name: work-section
    label: Work Section
    type: file
    path: src/content/homeSections/work.md
    fields:
      - name: title
        label: Title
        type: string
      - name: order
        label: Order
        type: number
      - name: section
        label: Section Type
        type: string
      - name: body
        label: Content
        type: rich-text

  - name: now-section
    label: Now Section
    type: file
    path: src/content/homeSections/now.md
    fields:
      - name: title
        label: Title
        type: string
      - name: order
        label: Order
        type: number
      - name: section
        label: Section Type
        type: string
      - name: body
        label: Content
        type: rich-text