media:
  - name: blog-images
    label: Blog Images
    input: public/images/blog
    output: /images/blog
    path: /images/blog

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: src/content/posts
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
      - name: pubDate
        label: Publication Date
        type: date
      - name: author
        label: Author
        type: string
      - name: image
        label: Featured Image
        type: object
        fields:
          - name: url
            label: Image URL
            type: string
          - name: alt
            label: Alt Text
            type: string
      - name: tags
        label: Tags
        type: list
      - name: body
        label: Content
        type: rich-text
        required: true

  - name: homeSections
    label: Home Page Sections
    type: collection
    path: src/content/homeSections
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: order
        label: Order
        type: number
        required: true
      - name: section
        label: Section Type
        type: select
        required: true
        options:
          values: [hero, about, work, now]